# Generated by Django 5.0.3 on 2024-04-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_bngjobs_punejobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bngjobs',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='address',
            field=models.TextField(),
        ),
    ]
